name: Build Python image

on:
  push:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      image: python
      tag: "3"
