name: Build Python image

on:
  push:
    paths:
      - src/python/**
      - .github/workflows/build-python.yml
      - .github/workflows/reusable-build.yml
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      image: python
      tag: "3"
