name: Build image

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      tag:
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_REPOSITORY: ${{ github.repository }}
  IMAGE_NAME: ${{ inputs.image }}
  IMAGE_TAG: ${{ inputs.tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: tags
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.IMAGE_TAG }}
      - name: Image metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          labels: |
            me.dusansimic.devcontainers.${{ env.IMAGE_NAME }}.version=${{ env.IMAGE_TAG }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.ref_type == 'tag' && steps.tags.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
